### ISSUE TITLE
Embeddings not working in kcpp > 1.99.4

### ISSUE THREAD

**Issue by truekry** [LostRuins/koboldcpp#1877]
Describe the Issue:
For every version after 1.99.4 I get an error when using vector embeddings that reads:
```
Generating Embeddings for 96 tokens...
Text Embeddings Generated 1024 values in 0.28s.
Error: Expecting value: line 1 column2 (char 1) 
```
I tried different models like:
mxbai-embed-large-v1-f16
snowflake-arctic-embed-l-v2.0
snowflake-arctic-embed-m-long
All work fine in 1.99.4

Additional Information:
OS: Win 11
CPU: AMD Ryzen 7 4800H
GPU: Nvidia 2060 6GB

Start param:
`(admin=False, admindir='', adminpassword='', analyze='', benchmark=None, blasbatchsize=512, blasthreads=None, chatcompletionsadapter=None, cli=False, config=['1.kcpps'], contextsize=8192, debugmode=0, defaultgenamt=512, draftamount=8, draftgpulayers=999, draftgpusplit=None, draftmodel=None, embeddingsgpu=False, embeddingsmaxctx=0, embeddingsmodel='D:/AI/snowflake-arctic-embed-l-v2.0-q6_k.gguf', enableguidance=False, exportconfig='', exporttemplate='', failsafe=False, flashattention=True, forceversion=0, foreground=False, genlimit=0, gpulayers=14, highpriority=False, hordeconfig=None, hordegenlen=0, hordekey='', hordemaxctx=0, hordemodelname='', hordeworkername='', host='localhost', ignoremissing=False, istemplate=False, launch=False, lora=None, loramult=1.0, maingpu=-1, maxrequestsize=32, mmproj=None, mmprojcpu=False, model=[], model_param='D:/AI/1.gguf', moecpu=0, moeexperts=-1, multiplayer=False, multiuser=0, noavx2=False, noblas=False, nobostoken=False, nocertify=False, nofastforward=False, nommap=False, nomodel=False, noshift=False, onready='', overridekv=None, overridenativecontext=0, overridetensors=None, password=None, port=5001, port_param=5001, preloadstory=None, prompt='', quantkv=0, quiet=True, ratelimit=0, remotetunnel=False, ropeconfig=[0.0, 10000.0], savedatafile=None, sdclamped=0, sdclampedsoft=0, sdclipg='', sdclipl='', sdconfig=None, sdconvdirect='off', sdflashattention=False, sdlora='', sdloramult=1.0, sdmodel='', sdnotile=False, sdphotomaker='', sdquant=0, sdt5xxl='', sdthreads=7, sdtiledvae=768, sdvae='', sdvaeauto=False, showgui=False, singleinstance=False, skiplauncher=False, smartcontext=True, ssl=None, tensor_split=None, threads=7, ttsgpu=False, ttsmaxlen=4096, ttsmodel='', ttsthreads=0, ttswavtokenizer='', unpack='', useclblast=None, usecpu=False, usecuda=['lowvram', '0', 'mmq'], usemlock=False, usemmap=False, useswa=False, usevulkan=None, version=False, visionmaxres=1024, websearch=False, whispermodel='')`

**Comment by LostRuins** [comment]
I have recently tried and embeddings is working fine. Can you try the following: 
1. Skip loading of your main model 1.gguf first, I don't know how large it is, but lets just try with embeddings alone. 
2. Try generate embeddings using http://localhost:5001/api#/api%2Fextra/post_api_extra_embeddings with a known payload
```
{
  "model": "kcpp",
  "input": "Niko the Kobold is in town today.",
  "truncate": true
}
```

does it work?

**Comment by truekry** [comment]
I tried the test with and without main gguf, both worked.

**Comment by LostRuins** [comment]
Alright, so I guess this is resolved then?

**Comment by truekry** [comment]
Sadly no. When I use it in a real scenario, I still get the issue.

**Comment by LostRuins** [comment]
Then i guess you need to see exactly what input is causing it to fail... if you know what string is a problem let me know

**Comment by truekry** [comment]
Whatever was wrong, its now gone in 1.104. Everything works fine now. I changed nothing on my setup or setting, just loaded the new version.
