### ISSUE TITLE
Broken cmake

### ISSUE THREAD

**Issue by Jakub-S-K** [LostRuins/koboldcpp#212]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Yes ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ Yes ] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ Yes ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ Yes ] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Please provide a detailed written description of what you were trying to do, and what you expected `llama.cpp` to do.
I was trying to compile latest full featured version.

# Current Behavior

Please provide a detailed written description of what `llama.cpp` did, instead.
As build with `make LLAMA_CUBLAS=1` didn't work exactly like in #169 
`koboldcpp.so: undefined symbol: ggml_cuda_mul_mat_get_wsize` at runtime.
I wanted to use cmake, because when I encountered that issue first it resolved all problems.
But in CMakeLists.txt line:52 there is `include(${CMAKE_CURRENT_SOURCE_DIR}/scripts/build-info.cmake)`
And as I saw in Latest commit `1ddbb9acd97954036044a005b79250a5d2d8b3c3` There is no more `scripts` directory which in return breaks cmake. This is my first issue here and maybe I am doing something very wrong.
# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using, e.g. for Linux:

`$ lscpu`
```Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         48 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  16
  On-line CPU(s) list:   0-15
Vendor ID:               AuthenticAMD
  Model name:            AMD Ryzen 7 5800H with Radeon Graphics
    CPU family:          25
    Model:               80
    Thread(s) per core:  2
    Core(s) per socket:  8
    Socket(s):           1
    Stepping:            0
    Frequency boost:     enabled
    CPU(s) scaling MHz:  37%
    CPU max MHz:         4462.5000
    CPU min MHz:         1200.0000
    BogoMIPS:            6390.61
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_op
                         t pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma c
                         x16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnow
                         prefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba
                          ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt x
                         savec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt l
                         brv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec
                         _ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
Virtualization features:
  Virtualization:        AMD-V
Caches (sum of all):
  L1d:                   256 KiB (8 instances)
  L1i:                   256 KiB (8 instances)
  L2:                    4 MiB (8 instances)
  L3:                    16 MiB (1 instance)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-15```
* Operating System, e.g. for Linux:

`$ uname -a`
`Linux kaori 6.3.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 30 May 2023 13:44:01 +0000 x86_64 GNU/Linux`
* SDK version, e.g. for Linux:

```
$ python3 --version
Python 3.11.3
$ make --version
GNU Make 4.4.1
$ g++ --version
g++ (GCC) 13.1.1 20230429
```

**Comment by LostRuins** [comment]
Apologies for that, was doing some cleaning up and and removed a few files. Can you pull and try again? it should work now.

**Comment by Jakub-S-K** [comment]
Sorry for late response, it compiles now, but even kobold.so built with cmake still throws 
```koboldcpp.so: undefined symbol: ggml_cuda_mul_mat_get_wsize```

How to properly build and start kobold.cpp with cuBlas? Today I tried ```openblas``` build and it works as expected, ```cublast``` also works but I've encountered something strange, ```--gpulayers``` are bigger now? Before I could offload around 18 layers with 2048 context to gpu but now on ```cublast``` max is around 11. 
Really strange behaviour.

**Comment by AlphaAtlas** [comment]
Are there any errors that pop up when you build kobold? I have gotten the ggml_cuda_mul_mat_get_wsize error when failing to find a cuda lib, or when trying to build with openblas and cublas at the same time (which you cannot do)

**Comment by Jakub-S-K** [comment]
There aren't any errors, but here is a compilation logs [Pastebin Logs](https://pastebin.com/Z4nMK8uq), there are some warnings concerning ggml_cuda_mul_mat_get_wsize but they are only pointer casting ones. 
I've checked `/opt/cuda/` and all lib are there in respective locations as it worked earlier. I'll try earlier commit and then investigate installed packages on said Arch Linux maybe something happened after update?

**Comment by AlphaAtlas** [comment]
Actually I am having build issues on Arch linux now too :thinking:

**Comment by LostRuins** [comment]
Sorry for the mess - I've been trying to refactor some of the cuda code out because the upstream cuda kernel removed some functions that the old library was using. I have some changes in my experimental branch which I want to push to main, but I have not had a chance to properly test them yet.

**Comment by AlphaAtlas** [comment]
Some upstream stuff in llama.cpp is a work in progress anyway. :+1:  Currently llama-cpp-python segfaults for me without a manual edit to ggml.c, and apparently cuda is outputting gibberish in some situations.

**Comment by AlphaAtlas** [comment]
Yeah, this latest cmake is working for me on Arch linux, with CUDA :+1:

**Comment by Jakub-S-K** [comment]
Same here, now everything works.
