### ISSUE TITLE
[Bug]  Share Story URL function does not work on non-horde addresses

### ISSUE THREAD

**Issue by VL4DST3R** [LostRuins/koboldcpp#491]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Current/Expected Behavior

Using the "Share" function to generate a URL with the embedded story in it only works if opened on the provided horde website (https://lite.koboldai.net/?). If i try to replace it with localhost or my IP it just opens an empty/previously cached instance of the page, effectively ignoring the `?s=XXXXXXXXX` part appended to the url.

**Comment by LostRuins** [comment]
Will be fixed in the next version

**Comment by LostRuins** [comment]
Fixed.

**Comment by VL4DST3R** [comment]
> Fixed.

Tested it on the latest version and it still doesn't work. Also the url is still pointing to the swarm regardless of where you're running the instance from.

**Comment by VL4DST3R** [comment]
It works but the url is still pointing to the swarm regardless of where you're running the instance from. Can this be addressed as well? Since most likely you will want to distribute this on the same platform you made it on.

**Comment by LostRuins** [comment]
Erm, that's kind of the point of "share"... if it was a localhost url or LAN url, you would not be able to open it on a different device on another network.

If you've hosted it publicly, what you can do is to simply replace the https://lite.koboldai.net with your own custom server URL.

**Comment by VL4DST3R** [comment]
> If you've hosted it publicly, what you can do is to simply replace the https://lite.koboldai.net/ with your own custom server URL.

Yeah, that's what I'm doing (hosting publicly) and indeed manually edited the link to test that indeed it works, but I figured it was a given that if you plan on sharing such a url with someone, you are doing so from something that can be accessed publicly (be it the swarm OR another address, and thus, use the current address in the link generation)

Look, it's not that big of a deal really, as you said, you just have to manually edit the URL and it works just fine, but it's a bit irksome it constantly links to the swarm especially when you have to deal with less tech-savvy friends that get confused why it suddenly opens to a different url.

The point of the ticket was to allow this to work for self-hosted stuff, which hopefully included the url generation itself.

**Comment by LostRuins** [comment]
Yup unfortunately Kobold Lite has no way of telling whether your current server is a public exposed one or private instance.

**Comment by VL4DST3R** [comment]
I still think that it makes more sense (intuitively) that it should use whatever current (exposed or not) url. Maybe use swarm only if specifically ran on `localhost` and otherwise use the current address?
