### ISSUE TITLE
"Inverted Colors" setting inverts images too

### ISSUE THREAD

**Issue by iScriptLex** [LostRuins/koboldcpp#616]
When "Inverted colors" flag is set in the settings, not only the background and text colors are inverted, but also the generated images. As a result, the images look terrible:
![2024-01-12-231734_1017x594_scrot](https://github.com/LostRuins/koboldcpp/assets/69735450/182d59dc-1359-4932-9679-2488d9428a7b)
That's how the same image should like:
![Untitled](https://github.com/LostRuins/koboldcpp/assets/69735450/3bf1a7ed-bcd0-4db1-941c-4ede173136f2)

Is there a way to make a light color scheme so that the images look normal?

**Comment by LostRuins** [comment]
Good point. I will fix it.

**Comment by LostRuins** [comment]
Fixed in 1.56

**Comment by iScriptLex** [comment]
> Fixed in 1.56

Partially fixed. The image itself is not inverted, but if you click on it, a window with an inverted version will pop up:
![2024-02-05-124200_1009x782_scrot](https://github.com/LostRuins/koboldcpp/assets/69735450/20f52123-ca7d-4b4d-8f9c-969ca587acf0)

**Comment by LostRuins** [comment]
Should be fully fixed
